# Generated by Django 2.1 on 2018-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvvrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
